swagger: "2.0"
info:
  description: "API Manter Produto"
  version: "1.0.0"
  title: "Serviço Manter Produtos"
host: "produto.com"
basePath: "/"
schemes:
  - https
  - http
paths:
  /produto:
    get:
      summary: "Retorna todos os produtos"
      operationId: listarTodosProdutos
      produces:
        - application/json
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Produto'
    post:
      summary: "Insere os dados do Produto"
      operationId: inserirProduto
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "product"
          description: "Contém os dados do produto que serão registrados na Base"
          required: true
          schema:
            $ref: "#/definitions/Produto"
      responses:
        "201":
          description: "Produto Inserido com Sucesso"
          schema:
            $ref: '#/definitions/Produto'
    put:
      summary: "Altera os dados do Produto"
      operationId: atualizarProduto
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "product"
          description: "Contém os dados do produto que serão alterados na Base"
          required: true
          schema:
            $ref: "#/definitions/Produto"
      responses:
        "201":
          description: "Produto Alterado com Sucesso!"
          schema:
            $ref: '#/definitions/Produto'

  /produto/id:
    get:
      summary: "Retorna o Produto com base no seu Id"
      operationId: obterProdutoId
      produces:
        - application/json
      parameters:
        - name: "idProduto"
          in: "query"
          description: "Identificador do Produto"
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "Operação Realizada com Sucesso!"
          schema:
            $ref: '#/definitions/Produto'
    delete:
      summary: "Remove o Produto com base no seu Id"
      operationId: excluirProdutoId
      produces:
        - application/json
      parameters:
        - name: "idProduto"
          in: "query"
          description: "Identificador do Produto"
          type: "integer"
          format: "int32"
      responses:
        "204":
          description: "Produto Excluído com Sucesso!"

  /produto/filtros:
    get:
      summary: "Retorna todos os produtos com base nos filtros informados pelo usuário"
      operationId: listarTodosProdutosFiltros
      produces:
        - application/json
      parameters:
        - name: "nome"
          in: "query"
          description: "Nome do Produto"
          type: "string"
        - name: "sinal"
          in: "query"
          description: "Sinal indicativo de >, <, >= ou <= para o preço do Produto"
          type: "string"
        - name: "preco"
          in: "query"
          description: "Preço do Produto"
          type: "number"
          format: "double"
        - name: "situacao"
          in: "query"
          description: "Situação do Produto"
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "Operação Realizada com Sucesso!"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Produto'

definitions:
  Produto:
    type: object
    properties:
      idproduto:
        type: integer
        format: int32
      nome:
        type: string
      descricao:
        type: string
      preco:
        type: number
        format: double
      situacao:
        type: integer
        format: int32
